# Generated by Django 4.0.6 on 2022-07-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuncionarioModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('cargo', models.IntegerField(choices=[(1, 'Modelador'), (2, 'Auxiliar de Modelador'), (3, 'Forneiro'), (4, 'Macheiro'), (5, 'Rebarbador'), (6, 'Ajudante'), (7, 'Operador de Máquina'), (8, 'Assistente RH'), (9, 'Assistente Adm'), (10, 'PCP')], verbose_name='Cargo')),
                ('CPF', models.CharField(max_length=11, verbose_name='CPF')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='E-mail')),
                ('tel', models.CharField(max_length=11, verbose_name='Telefone')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade/Estado')),
                ('rua', models.CharField(max_length=150, verbose_name='Rua - Número')),
                ('conta', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número da Conta')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
    ]
