# Generated by Django 4.0.6 on 2022-07-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionariomodels',
            name='salario',
            field=models.PositiveIntegerField(default=1, max_length=10, verbose_name='Salário'),
            preserve_default=False,
        ),
    ]
