# Generated by Django 4.0.6 on 2022-07-26 01:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('tel', models.CharField(max_length=11, verbose_name='Telefone')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade/Estado')),
                ('rua', models.CharField(max_length=150, verbose_name='Rua - Número')),
                ('conta', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número da Conta')),
            ],
        ),
        migrations.CreateModel(
            name='modelos1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, verbose_name='Número do Modelo')),
                ('material', models.IntegerField(choices=[(1, 'Madeira'), (2, 'Compensado/MDF'), (3, 'Isopor')], verbose_name='Material do Modelo')),
                ('reforma', models.IntegerField(choices=[(1, 'Sim'), (2, 'Não')], verbose_name='Reformar Modelo?')),
                ('fundir', models.IntegerField(choices=[(1, 'Sim'), (2, 'Não')], verbose_name='Peça para Fundir?')),
                ('matfund', models.IntegerField(blank=True, choices=[(1, 'Aluminio'), (2, 'Ferro'), (3, 'Aço'), (4, 'Aço Inox'), (5, 'Ferro Branco')], null=True, verbose_name='Material do Fundido')),
                ('quantFund', models.IntegerField(blank=True, null=True, verbose_name='Quatidade de Peças')),
                ('pesoFund', models.FloatField(blank=True, null=True, verbose_name='Peso por Peça')),
                ('dataEnt', models.DateTimeField(verbose_name='Dia de Entrada do Serviço')),
                ('dataProd', models.DateTimeField(verbose_name='Data do Início do Serviço')),
                ('dataFim', models.DateTimeField(verbose_name='Data do Serviço Finalizado')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Serviço')),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.cliente')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
    ]
