# Generated by Django 4.0.6 on 2022-07-27 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0002_modelomodels_rename_cliente_clientemodels_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelomodels',
            name='nome',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicos.clientemodels', verbose_name='Cliente'),
        ),
    ]
