# Generated by Django 4.0.6 on 2022-07-27 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicos', '0003_alter_modelomodels_nome'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientemodels',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
    ]
