# Generated by Django 4.0.6 on 2022-07-26 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Fornecedor')),
                ('tipoMat', models.IntegerField(choices=[(1, 'Madeira/MDF/Compensado'), (2, 'Isopor'), (3, 'Fundição/Consumíveis'), (4, 'Escritório/Ferramenta/Consumíveis')], verbose_name='Tipo do Fornecedor')),
                ('cnpj', models.CharField(max_length=14, verbose_name='CNPJ')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('tel', models.CharField(max_length=11, verbose_name='Telefone')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade/Estado')),
                ('rua', models.CharField(max_length=150, verbose_name='Rua - Número')),
                ('conta', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número da Conta')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.CreateModel(
            name='MaterialModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mat', models.CharField(max_length=150, verbose_name='Material')),
                ('nome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.fornecedormodels', verbose_name='Fornecedor')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiais',
            },
        ),
    ]
