# Generated by Django 4.0.6 on 2022-07-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialmodels',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Valor'),
            preserve_default=False,
        ),
    ]
