# Generated by Django 4.0.6 on 2022-07-26 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0002_materialmodels_valor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.fornecedormodels', verbose_name='Fornecedor')),
                ('material', models.ManyToManyField(to='compras.materialmodels')),
            ],
        ),
    ]
